### ISSUE TITLE
Cannot set property console of #<Object> which has only a getter on npm run dev

### ISSUE THREAD

**Issue by arshad115** [manniL/lichter.io#39]
I am unable to run the dev version. Here is the output:

```
> nuxt


 FATAL  Cannot set property console of #<Object> which has only a getter                                                                                                                                                                                      01:42:36

  at Object.<anonymous> (node_modules\vue-meta\dist\vue-meta.common.js:133:33)
  at Module._compile (module.js:652:30)
  at Object.Module._extensions..js (module.js:663:10)
  at Module.load (module.js:565:32)
  at tryModuleLoad (module.js:505:12)
  at Function.Module._load (module.js:497:3)
  at Module.require (module.js:596:17)
  at require (internal/module.js:11:18)
  at Object.<anonymous> (node_modules\@nuxt\vue-renderer-edge\dist\vue-renderer.js:20:33)
  at Module._compile (module.js:652:30)


   ╭─────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                 │
   │   ✖ Nuxt Fatal Error                                                            │
   │                                                                                 │
   │   TypeError: Cannot set property console of #<Object> which has only a getter   │
   │                                                                                 │
   ╰─────────────────────────────────────────────────────────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lichter.io@3.1.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lichter.io@3.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by manniL** [comment]
Can't reproduce this locally :man_shrugging: 	You might want to try out `yarn` instead of npm as I don't have a `package-lock.json` but a `yarn.lock`.

**Comment by arshad115** [comment]
Worked with yarn and I also had to update node. Thank you :)
